//go:build ignore

package main

import (
	"fmt"
	"math"
	"os"
	"time"
)

func main() {
	levels := make([]int, 41)
	levels[0] = 0
	levels[1] = 200

	for level := 2; level < len(levels); level++ {
		previousXP := levels[level-1]
		levels[level] = int(math.Ceil(float64(previousXP) * 2))
	}

	timestamp := time.Now().Format("2006-01-02 15:04:05")
	output := `// Code generated by ../generators/level_xp.go on ` + timestamp + `. DO NOT EDIT.
	
package models

var xpForLevel = map[int]int{
`

	for level, xp := range levels {
		output += fmt.Sprintf("\t%d: %d,\n", level, xp)
	}

	output += "}"

	os.WriteFile("../models/level_xp_generated.go", []byte(output), 0644)
}
